#pragma once

// copy from glfw3.h

#define FOREST_MOUSE_BUTTON_1 0
#define FOREST_MOUSE_BUTTON_2 1
#define FOREST_MOUSE_BUTTON_3 2
#define FOREST_MOUSE_BUTTON_4 3
#define FOREST_MOUSE_BUTTON_5 4
#define FOREST_MOUSE_BUTTON_6 5
#define FOREST_MOUSE_BUTTON_7 6
#define FOREST_MOUSE_BUTTON_8 7
#define FOREST_MOUSE_BUTTON_LAST FOREST_MOUSE_BUTTON_8
#define FOREST_MOUSE_BUTTON_LEFT FOREST_MOUSE_BUTTON_1
#define FOREST_MOUSE_BUTTON_RIGHT FOREST_MOUSE_BUTTON_2
#define FOREST_MOUSE_BUTTON_MIDDLE FOREST_MOUSE_BUTTON_3